### ISSUE TITLE
KDE crashes on CFS data

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#11]
Various bugs come up: zero division error, some runtime errors in clustering, a segmentation fault in larger traces, errors when length of trace is too short

**Comment by Nate-Wessel** [comment]
Can you

**Comment by Nate-Wessel** [comment]
Can you give me some of the error outputs? Are they coming from Python or R?

**Comment by felipevh** [comment]
the error output is "segmentation fault" which is a C error

**Comment by Nate-Wessel** [comment]
Does it do this on the testing data? What function does it fail in?
