### ISSUE TITLE
Many long, obscure functions everywhere should be shortened

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#17]
In particular:
__init__ file reading should be handled elsewhere (part of issue #4 )
flush likewise part of issue #4 
get_days inner loop can be abstracted

refactor for readability:
get_known_subsets
get_activity_locations
break_trips
find_peaks
observe_neighbours

**Comment by Nate-Wessel** [comment]
It sounds like we should establish some coding standards before we get much further.

**Comment by felipevh** [comment]
Vague, going to open an issue for each function/method to be refactored
