### ISSUE TITLE
Output trip geometry file

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#18]
Coded as an additional column on the coordinates file, labeling each point to what trip/activity it corresponds to, if any.

Also, see if any standards exists for representing trip geometry

**Comment by Nate-Wessel** [comment]
We're just a couple steps away from having that. The classification is already stored with each point object and i think there might even be a column for it already in the output file.
 
There are lots of standards for representing line geometry. It may be best to just provide a trip number classification (activity sequence id?) along with each point classified as travel. People will want to convert into their preferred format.

**Comment by Nate-Wessel** [comment]
this is very similar to another issue.
