### ISSUE TITLE
Parallelize processing

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#20]
One user per core?

One potential issue here is the current high memory requirements for some users in the clustering step.

**Comment by felipevh** [comment]
made big progress here, just need to buffer the output so it doesn't come out as garbage

**Comment by felipevh** [comment]
Done. Parallelizes to use all cpus provided by os.cpu_count(). Output is still out of order, so for debugging you can turn off parallelism in config.multi_process

A possible solution would be to either preface each print statement with the users name, or change print statements to return strings

**Comment by Nate-Wessel** [comment]
I don't see this. Have you pushed yet?

**Comment by felipevh** [comment]
I hadn't pushed to master yet, should be up to date now
