### ISSUE TITLE
Limit the number of points sent to KDE

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#22]
We are using a KDE to estimate locations where more than 10 minutes has been spent in one spot. To do this, we feed in all the interpolated points. But we should know that we can't/shouldn't have any locations found where there are only interpolated points. The only reason we include them all is that it's an easier way to spread out time weights where they shouldn't be too concentrated on the original (sparse) input points. 

Better/smarter weight assignments to the original points should reduce the time spent in the KDE step.

**Comment by ljwolf** [comment]
on KDEs (maybe not directly relevant to this exact ticket), I talked with @mwidener at AAG, and asked about why he was doing the KDE in `R` over using something in python. I wanted to follow up on that. 

I'm not sure if y'all're comfortable with a `scikit-learn` dependency, but their [kernel density estimator](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/neighbors/kde.py#L24) is quite fast to train. You can get random samples from its surface using the `sample` method, and get log probabilities of arbitrary coordinates from its `score` method. If you want to estimate the bandwidth, using an arbitrary K-neighbors distance from `pysal.cg.KDTree` could be fast.

**Comment by Nate-Wessel** [comment]
@ljwolf Thanks for the tip! 

The R implementation doesn't seem ideal, but it's actually quite fast  and the code for passing data between the two was pretty painless. I'm adding a note in the code to suggest one of these packages if/when we need to revisit the function implementing the KDE.

**Comment by felipevh** [comment]
I think we identified trace.py/interpolate_segment as a possible culprit for this

**Comment by felipevh** [comment]
I've started working on this on my fork if you want to check it out. It broke multiprocessing (somehow?) but location detection got a lot better, while distance error got a bit worse in some cases, and better in others.

**Comment by Nate-Wessel** [comment]
By location detection then I take it you mean counts?

**Comment by felipevh** [comment]
Moved this to a new remote branch

**Comment by Nate-Wessel** [comment]
I think this has been adequately addressed for now. There's more to do on interpolation, but not in this issue :-)
