### ISSUE TITLE
Ground truth I-phone survey data

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#24]
Check with Mischa/Kyle to be sure the app is working again and how to know if it isn't.

**Comment by Nate-Wessel** [comment]
https://beta.itunes.apple.com/v1/invite/32172df78a0a4289bb81b3b7084593031eaccbeb1c7f4695921c83e692214f3049b290d1?ct=ZacharyPatterson1448243595&advp=10000&platform=ios

**Comment by mwidener** [comment]
what survey name?

**Comment by Nate-Wessel** [comment]
Try `UT1`. That's what it's been the last couple times.

**Comment by Nate-Wessel** [comment]
Felipe will get ground truth in Mexico so we can learn how to handle data from outside of Canada if we need to. 
Nate will develop a QGIS interface for ground-truth classifying data quickly.

**Comment by Nate-Wessel** [comment]
We now have survey data for three users, one week each. Need to ground-truth two of them yet.

**Comment by Nate-Wessel** [comment]
Only need to add/classify Felipe's data now.

**Comment by felipevh** [comment]
Closing since apparently my data was so sparse that it missed a 2 day, 400 km trip.
