### ISSUE TITLE
Timestamps are inconsistent across input and output files

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#32]
Not a major issue, but it does cause minor headaches and multiple different timestamp parsing functions.

**Comment by felipevh** [comment]
Really just episodes_ground_truth.csv

**Comment by Nate-Wessel** [comment]
lets just pick one format for consistency. or better yet, find a library to handle all this without parsing things ourselves?

**Comment by felipevh** [comment]
closed until itinerum outputs epoch times
