### ISSUE TITLE
Improve and/or refactor misc_funcs.py/kde 

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#36]
We've discussed changing the kde function to improve location detection accuracy, but short of that it should be refactored for readability.

**Comment by Nate-Wessel** [comment]
Actually, I also think this function is pretty readable... what's wrong with it? It's only as long as it is because working with the R interface takes some stuff. Otherwise it's really very simple and replaces an R function of the same name with essentially the same inputs.

**Comment by Nate-Wessel** [comment]
Can you make this issue more specific or close it?

**Comment by felipevh** [comment]
It seemed a little long when I looked at it, but after a second glance I think you're right.

**Comment by Nate-Wessel** [comment]
I actually did end up refactoring this a bit.
