### ISSUE TITLE
Improve data input efficiency

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#4]

**Comment by Nate-Wessel** [comment]
Hold input coordinates table in memory and subset efficiently for each user rather than reading the data in again.

**Comment by Nate-Wessel** [comment]
This is now also an issue for the survey_responses.csv file.

**Comment by Nate-Wessel** [comment]
Let's just get the home/work/school locations passed efficiently and we'll call this closed. 

We may also want to check that the CSV format (column order etc) isn't an unnecessary dependency.
