### ISSUE TITLE
Documentation and style guide

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#41]
We should come up with/adopt standards for documentation and style, and identify where we're lacking.

**Comment by felipevh** [comment]
I've added pep8.py in order to check style guidelines, and I'll be adding a script that checks all our python style for consistency. I've suppressed a couple of warning due to us using tabs instead of spaces.

**Comment by Nate-Wessel** [comment]
What is this? I have not heard of such things before. You'll have to explain in the next call..

**Comment by felipevh** [comment]
Will do, in short its a python style standard. The script just reads a
python file and lists the style errors. It should go a long way for
consistency and readability.

**Comment by felipevh** [comment]
Also life would be so much easier if we used spaces instead of tabs

**Comment by Nate-Wessel** [comment]
Convince me?

**Comment by felipevh** [comment]
Spaces are displayed consistently across platforms and contexts, tabs are variable width, making displaying code across multiple columns a hassle with tabs.

Spaces are inserted consistently across platforms and contexts, tabs are not. Pressing spacebar inserts 1 space no matter what, pressing tab can, depending on environment: insert 2,4, or 8 spaces, insert spaces until the current column is a multiple of 8, insert a tab character (which run in to the display problem), or insert a combination of tabs and spaces according to whatever arcane rules that environment has.

Also current python standards generally insist on spaces.

**Comment by mwidener** [comment]
Nerds

--
Michael Widener

**Comment by Nate-Wessel** [comment]
And:
https://stackoverflow.blog/2017/06/15/developers-use-spaces-make-money-use-tabs/

Pressing tab once should insert one tab, and no one will be able to tell me that that should not be the case. Though I admit the visual consistency is a benefit of spaces. 

You're a space cadet :-P

**Comment by felipevh** [comment]
Does that mean I'll get paid more if I convert all the tabs to spaces? /s

In a perfect world, pressing tab would insert one tab character, but that just isn't the case on most platforms. Also you can always put in a tab for display purposes as \t in a raw string (like the output of compare.py). Notice how when compare.py prints to terminal the columns line up? its because tabs are variable width.

Variable width is bad because it means you and I might be looking at different code depending on our platform, and since python cares so much about white space, it could be functionally different.

**Comment by felipevh** [comment]
Not to mention some platforms, including git under certain repo+user settings, will automatically change tabs to spaces and back again, depending on the client platform. Just say no to tabs

**Comment by Nate-Wessel** [comment]
Let's stick with tabs for now... it sounds like it will be easy to change to spaces if we decide to one day. 

There are a few places where tabs follow some code - usually a comment after a variable declaration - and I can see the variable spacing being an issue (it looks fine if you set the tabs = 3 spaces but not otherwise).

I'd be fine with having those refactored so that variable spacing doesn't produce any unpleasant results.
