### ISSUE TITLE
Note identical points in input data, somehow flag as more likely being error

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#42]
Android phones seem to produce many points at the same locations, perhaps when they are acquiring a signal or when the signal is weak. Most of these are basically crap though and should be discarded if they aren't already. This information should be used in the data cleaning stage to remove points that are repeated, with limited exceptions where points repeat just by chance due to rounding.

**Comment by Nate-Wessel** [comment]
I believe we are currently just popping out the middle of three repeated points because I assumed the times were different. There are cases where they are not! In these cases all but one identical point should be removed.

**Comment by Nate-Wessel** [comment]
Implemented. This actually removed a few hundred points for each of the iphone users!

**Comment by Nate-Wessel** [comment]
Oops. Thought this was another similar issue.

**Comment by felipevh** [comment]
I added a cleaning function to get rid of repeated locations, but it might need to be dealt with earlier in the kde.

**Comment by Nate-Wessel** [comment]
@felipevh I'm not sure you're in the right issue. I'm going to change the title to clear things up a bit..

**Comment by felipevh** [comment]
That makes more sense, thanks

**Comment by felipevh** [comment]
we currently check and count points with identical timestamps, which will also catch repeated points.

**Comment by Nate-Wessel** [comment]
That's a separate issue; right now we only check for repeated records, not for points reported at different times but the exact same location.

**Comment by Nate-Wessel** [comment]
Some of these points are actually *at* or very near activity locations though... I'm having second thoughts about removing them.

**Comment by Nate-Wessel** [comment]
In concord with my previous comment, a lot of these repeated locations are at or very very near home locations, as much time is spent there. I'm closing this issue as I'm not sure it's a good idea any more.
