### ISSUE TITLE
Add episode identification metrics to compare.py

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#55]
Should be similar metrics to unknown time detection.

**Comment by felipevh** [comment]
Correctly identified unknown time and activity time, as well as misidentified unknown time and activity time are currently being calculated. I'm unsure of what to put as the denominator to get a meaningful percentage, so there is a flag in config to toggle some options.

**Comment by Nate-Wessel** [comment]
What is the numerator? Some of the new options in the config file are not very clear to me...

**Comment by felipevh** [comment]
the options are either the total time (that both ground truth and the computed values cover) or the total time subtracting time that isn't relevant ie: for the percentage of correctly identified unknown time its 
correctly identified unknown time / (total time - true activity time)
noting that (total time - true activity time) is the same as (correctly identified unknown time + misidentified activity time)

The problem with the second option is that its redundant. The percent correctly identified unknown time + misidentified activity time will always sum to 100, as with misidentified unknown time and correctly identified activity time.

**Comment by Nate-Wessel** [comment]
So, here's a summary from our discussion: if we have..
````
TT | TF
--------
FT | FF
````
as the possible classifications for a time span, considered from the point of view of a classification category, then let `identified_time` be 
````
TT / ( TT + FT )
````
Or the percent of time actually true that is classified as true.

Let `misidentified_time` be
````
TF / ( FF + TF )
````
or the percent of time actually false but classified as true.

The range for `identified_time` and `misidentified_time` is 0 to 100%. If there is no time in the denominator however, we should return `NA`.

**Comment by Nate-Wessel** [comment]
This is done now, right?

**Comment by felipevh** [comment]
Yes
