### ISSUE TITLE
Repeated identical locations are being produced

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#56]
Look especially at user A and the 19 identical locations produced at Sid Smith, (-79.436071900000002,43.645137599999998).

**Comment by felipevh** [comment]
is it not a repeat of #42 ?

**Comment by Nate-Wessel** [comment]
No. This one has to do with the identification of multiple activity locations in the same spot. The other one proposes using repeated locations in the input data as an extra indicator of GPS accuracy. Precisely repeating GPS locations are extremely unlikely in theory, so that may indicate locations derived from e.g. a cell tower or wifi. 

Though the two may be related if one helps cause the other.

**Comment by Nate-Wessel** [comment]
Any progress on this yet?

**Comment by felipevh** [comment]
I'm cleaning them after the fact, but I can't make heads or tails of why the kde is making them after the fact.

**Comment by felipevh** [comment]
cleaned in trace.py\remove_repeated_locations. I'm ckosing, assuming we dob't want to move the cleaning elsewhere

**Comment by Nate-Wessel** [comment]
I'm going to reopen this until I have a chance to review your changes. I'd rather know why they're being generated than handle them after a bug!

**Comment by Nate-Wessel** [comment]
Yeah, this is not fixed yet. Because of the change to the location hashing, the equality comparison no longer removes locations.

**Comment by Nate-Wessel** [comment]
Resolved! The issue was indeed related to repeated locations in the input data.
