### ISSUE TITLE
Check location hashability

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#57]
trace.py's break_trips() uses set() on a list of locations. This requires locations to be hashable. 

The recent changes to location.py to add `__str__()` and `__eq__()` seem to be preventing this, throwing an error, so I commented them out to complete the merge. 

I don't fully understand what these functions do yet or how they affect hashing.

**Comment by felipevh** [comment]
hashing on object id now
