### ISSUE TITLE
Different points with identical timestamps

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#58]
This was a problem, but we're checking for it now. Weight shouldn't be an issue here, but it is concerning that itinerum thinks the user is in two (albeit close together) locations at once.

**Comment by Nate-Wessel** [comment]
So is this an issue for our code or Itinerum?

**Comment by felipevh** [comment]
I'd say its itinerum, but we have to deal with it (assign weights, interpolate points) somehow for the time being.

**Comment by Nate-Wessel** [comment]
How many such points are there? If it's just a few then I say we pick one and toss the other. Shouldn't make much difference which.

**Comment by felipevh** [comment]
right now we're keepung both but not assigning any additional weight

**Comment by felipevh** [comment]
closing since we check for this, and should be dealt with in itinerum
