### ISSUE TITLE
KDE run on zero points causes crash

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#59]
An error generated by some of the CFS 2016 and 2017 users. They can be isolated by running etc/isolate.py on the corresponding csv files.

**Comment by Nate-Wessel** [comment]
What exactly is the error?

**Comment by felipevh** [comment]
[out_main.txt](https://github.com/SAUSy-Lab/itinerum-trip-breaker/files/2195792/out_main.txt)

**Comment by Nate-Wessel** [comment]
So the problem there is not the weights but that the KDE function is not being given any input. It's being fed an empty list. 
Also note that `-1 gap(s) found in data`, so something is going wrong a bit earlier.

**Comment by Nate-Wessel** [comment]
By the way, I don't have this data, so I'm not able to debug it.

**Comment by felipevh** [comment]
Noted. This seems to be an issue with break_trips then, so hopefully it'll resolve along with issue #53
