### ISSUE TITLE
Better documentation needed in config file

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#60]
E.g. 
````
# weight coefficient
weight_coef = 1
````
is not clear to me. This and other configuration parameters should be given fuller names so they're a bit less cryptic when they appear in the code. Make sure to fully document the purpose of every parameter.

**Comment by felipevh** [comment]
done! sometimes these things seem clear to me at the time, it helps to have a second pair if eyes
