### ISSUE TITLE
Start interpolating again with smarter weighting scheme

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#69]
I'm running the script on the training data (`inputs/`) and I was trying to make sure that `ts_str()` was working properly. The only place it's actually called was in the `pair_interpolation` function, but I realized this code is not even being run. What happened to interpolating the points??

**Comment by felipevh** [comment]
fixed a lot of bugs that come from timestamp changes. Still sorting out a few that affect weight distribution.
Interpolation runs bug free, but weight distribution is disabled.

**Comment by Nate-Wessel** [comment]
Can you push the changes with just a uniform weight distribution? I want something to start playing with.

**Comment by Nate-Wessel** [comment]
Per discussion, this is now to be implemented in the `pair_interpolation` function via the assignment of timestamps to synthetic points.

Weights are applied based on timestamps later.
