### ISSUE TITLE
Remove activities shorter than threshold

### ISSUE THREAD

**Issue by Nate-Wessel** [SAUSy-Lab/itinerum-trip-breaker#71]
We should not get any stationary activities shorter than `minimum_activity_time`. Any activity shorter than this should be reallocated to travel, possibly with a rerun of the HMM.

**Comment by felipevh** [comment]
Current marking these activities as travel time. It results in the same number of episodes, many of which are back to back travel

**Comment by Nate-Wessel** [comment]
Does this effect the point state classification?

**Comment by Nate-Wessel** [comment]
It's not ideal to have sequential travel episodes...

**Comment by Nate-Wessel** [comment]
I've changed this such that when episodes are removed the episodes around them are merged correctly to fill the gap.
