### ISSUE TITLE
Platform differences in episodes output

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#79]
@felipevh gets output inconsistent with @Nate-Wessel in episodes.csv

The problem is likely in trace/remove_short_stationary_episodes, but requires further comparison between platforms

**Comment by Nate-Wessel** [comment]
@felipevh, are we going to debug this yet? My platform is getting the desired results, so unless your platform is going to continue to be in play here, we may want to downgrade this to a thing-to-watch-out-for.
