### ISSUE TITLE
Generate output quality/testing metrics comparing to ground-truth data

### ISSUE THREAD

**Issue by felipevh** [SAUSy-Lab/itinerum-trip-breaker#8]
We need ground truth data

**Comment by felipevh** [comment]
Compare processed itinerum data to ground truth data. Compute a percentage similarity in order to evaluate accuracy of our processing algorithms.

In addition to percentage similarity we want confidence percentage for each user/episode etc

**Comment by Nate-Wessel** [comment]
Quality metrics to start with:

1. Unknown time classification
  * Percent of unknown time correctly identified
  * Percent of total survey time (minus actual unknown time) misidentified as unknown

2. Location detection
  * This can be implemented as follows:
    1. calculate full distance matrix between the two sets of locations, true and discovered 
    2. select the minimum from the matrix and set those two locations aside. Repeat until the matrix is null
    3. report the average of the minimum distances *and* the number of locations not matched as a signed integer. 0 = perfect 1 to 1 matching, -1 = one true location not discovered, 1 = 1 false positive. 

Let's consider this issue closed once these metrics are completed and add a new issue for additional metrics pertaining to trip and activity classification, etc.

**Comment by mwidener** [comment]
Ensure that ground truth-ed activity locations are captured by algorithm. Percent of activity sites in reality vs. activity sites captured by algorithm.

**Comment by mwidener** [comment]
\m/

**Comment by felipevh** [comment]
The pairing algorithm for minimum distances I'm using doesn't seem right to me

**Comment by Nate-Wessel** [comment]
@felipevh do you mean the one I described above, or your implementation of it? What's wrong?

**Comment by felipevh** [comment]
My implementation of it. I misunderstood what you wrote

**Comment by felipevh** [comment]
The above metrics are implemented, closing this issue until we agree on some new ones.
